dubbo:
  application:
    name: user-consumer
    qos-enable: false
  registry:
    address: nacos://192.168.149.1:8848?namespace=c3ca4e7b-10ec-4990-a494-acf5be82542d&username=nacos&password=nacos
  protocol:
    port: 9091
